# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_KEE5IGCBafEKWDRwu1nbTrOnFc5ojH
"""

!pip install textblob wordcloud nltk

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from textblob import TextBlob
from wordcloud import WordCloud

import nltk
import re

from nltk.corpus import stopwords

nltk.download('stopwords')

df = pd.read_csv("amazon_com-product_reviews__20200101_20200331_sample.csv")

df.head()

df.columns

review_column = 'Review Title'

df = df[[review_column]].dropna()

df.head()

df = df.drop_duplicates()

df.reset_index(drop=True, inplace=True)

stop_words = set(stopwords.words('english'))

def clean_text(text):

    text = str(text).lower()

    # Remove links
    text = re.sub(r'http\\S+', '', text)

    # Remove special characters
    text = re.sub(r'[^a-zA-Z ]', '', text)

    # Remove extra spaces
    text = re.sub(r'\\s+', ' ', text)

    # Remove stopwords
    words = text.split()

    words = [word for word in words if word not in stop_words]

    return " ".join(words)

df['Cleaned_Review'] = df[review_column].apply(clean_text)

df.head()

def get_sentiment(text):

    analysis = TextBlob(text)

    polarity = analysis.sentiment.polarity

    if polarity > 0:

        return "Positive"

    elif polarity < 0:

        return "Negative"

    else:

        return "Neutral"

df['Sentiment'] = df['Cleaned_Review'].apply(get_sentiment)

df.head()

df['Sentiment'].value_counts()

plt.figure(figsize=(6,4))

sns.countplot(x='Sentiment', data=df)

plt.title("Amazon Reviews Sentiment Analysis")

plt.show()

df['Sentiment'].value_counts().plot.pie(
    autopct='%1.1f%%'
)

plt.ylabel('')

plt.title("Sentiment Distribution")

plt.show()

df['Polarity'] = df['Cleaned_Review'].apply(
    lambda x: TextBlob(x).sentiment.polarity
)

df[['Cleaned_Review','Polarity']].head()

positive_reviews = " ".join(
    df[df['Sentiment']=="Positive"]['Cleaned_Review']
)

wordcloud = WordCloud(
    width=800,
    height=400,
    background_color='white'
).generate(positive_reviews)

plt.figure(figsize=(12,6))

plt.imshow(wordcloud)

plt.axis('off')

plt.title("Positive Review Word Cloud")

plt.show()

negative_reviews = " ".join(
    df[df['Sentiment']=="Negative"]['Cleaned_Review']
)

wordcloud = WordCloud(
    width=800,
    height=400,
    background_color='white'
).generate(negative_reviews)

plt.figure(figsize=(12,6))

plt.imshow(wordcloud)

plt.axis('off')

plt.title("Negative Review Word Cloud")

plt.show()

df[[review_column,'Sentiment']].head(10)

positive = df[df['Sentiment']=="Positive"].shape[0]

negative = df[df['Sentiment']=="Negative"].shape[0]

neutral = df[df['Sentiment']=="Neutral"].shape[0]

print("BUSINESS INSIGHTS\\n")

print("Positive Reviews :", positive)

print("Negative Reviews :", negative)

print("Neutral Reviews :", neutral)

if positive > negative:

    print("\\nMost customers are satisfied with the products.")

if negative > 0:

    print("Some customers reported issues that companies should improve.")

print("\\nCompanies can use sentiment analysis for:")

print("- Product Improvement")

print("- Marketing Strategy")

print("- Customer Satisfaction Analysis")

print("- Public Opinion Tracking")