# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/142XzA0u4Fh20DwvshC9Cf_K_7LlTPLtk

# Questions for Analysis

1. Does Netflix contain more Movies or TV Shows?
2. Which country produces the most Netflix content?
3. Which genres are most common on Netflix?
4. How has Netflix content grown over the years?
5. Which ratings are most common?
6. Which directors appear most frequently?
"""

import pandas as pd
df = pd.read_csv('netflix_titles.csv')
df.head()

df.info()

df.shape

df.columns

df.isnull().sum()

"""## Observations

- The dataset contains movies and TV shows information.
- Some columns contain missing values.
- The dataset includes categorical and numerical data.
- Important columns are type, country, release_year, rating, and listed_in.
"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x='type', data=df)

plt.title('Movies vs TV Shows')

plt.show()

"""## Insight

Netflix contains more movies than TV shows.
"""

top_country = df['country'].value_counts().head(10)

top_country.plot(kind='bar')

plt.title('Top 10 Countries')

plt.show()

"""## Insight

United States produces the highest amount of Netflix content.
"""

df['release_year'].value_counts().sort_index().plot()

plt.title('Content Release Trend')

plt.xlabel('Year')

plt.ylabel('Count')

plt.show()

"""## Insight

Netflix content production increased rapidly after 2015.
"""

top_genres = df['listed_in'].value_counts().head(10)

top_genres.plot(kind='barh')

plt.title('Top Genres')

plt.show()

"""## Insight

Drama and International Movies are among the most popular genres.

# Analysis of Ratings

This analysis identifies the most common content ratings available on Netflix.
"""

top_ratings = df['rating'].value_counts().head(10)

top_ratings.plot(kind='bar')

plt.title('Most Common Netflix Ratings')

plt.xlabel('Ratings')

plt.ylabel('Count')

plt.show()

"""# Insight

TV-MA and TV-14 are among the most common ratings on Netflix.

This indicates that Netflix contains a large amount of mature and teen-oriented content.

# Director Analysis

This analysis identifies directors who appear most frequently on Netflix.
"""

top_directors = df['director'].value_counts().head(10)

top_directors.plot(kind='barh')

plt.title('Top 10 Directors on Netflix')

plt.xlabel('Count')

plt.ylabel('Director')

plt.show()

"""# Insight

Some directors contribute significantly more content than others on Netflix.

This shows Netflix collaborates repeatedly with certain popular directors.

# Hypothesis

Movies are more common than TV Shows on Netflix.
"""

df['type'].value_counts()

"""## Result

The hypothesis is correct because the dataset shows significantly more movies than TV shows.

# Hypothesis

Netflix content increased after 2015.
"""

df['release_year'].value_counts().sort_index().plot(figsize=(12,6))

plt.title('Netflix Content Release Trend')

plt.xlabel('Year')

plt.ylabel('Number of Content')

plt.show()

"""# Validation Result

The graph shows that Netflix content production increased significantly after 2015.

Therefore, the hypothesis is validated.

# Hypothesis

The USA contributes the highest Netflix content.
"""

top_country = df['country'].value_counts().head(10)

top_country.plot(kind='bar')

plt.title('Top 10 Countries')

plt.show()

"""# Validation Result

The graph shows that USA contributes the highest Netflix content.

Therefore, the hypothesis is validated.
"""

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df['country'].fillna('Unknown', inplace=True)

"""## Data Issues Found

- Missing values were present in some columns.
- Duplicate rows were checked and removed.
- Missing country values were replaced with "Unknown".

# Conclusion

The Exploratory Data Analysis (EDA) of the Netflix dataset provided valuable insights into Netflix content trends and patterns.

The analysis showed that Netflix contains more Movies than TV Shows. The United States was identified as the highest contributor of Netflix content. Content production on Netflix increased rapidly after 2015, showing the platform’s significant growth in recent years.

Genre analysis revealed that Drama and International Movies are among the most common genres available on Netflix. Rating analysis indicated that TV-MA and TV-14 are the most frequently used ratings, suggesting that Netflix mainly targets mature and teenage audiences.

The director analysis showed that some directors appear more frequently than others, indicating repeated collaborations with Netflix.

During data cleaning, missing values and duplicate records were identified and handled appropriately to improve data quality and analysis accuracy.

Overall, this project helped in understanding Netflix’s content distribution, growth trends, audience targeting, and genre popularity using Exploratory Data Analysis and Data Visualization techniques.
"""